version: 3

vars:
    FIX: false
    DIFF: false
    BASE: main
    SNAPSHOT: false
    CHANGED:
        sh: git diff-ls {{.BASE}}
    PRETTIER_TARGET: '{{if eq .DIFF "false"}}.{{else}}{{.CHANGED | catLines}}{{end}}'
    ESLINT_TARGET: '{{if eq .DIFF "false"}}src{{else}}{{.CHANGED | catLines}}{{end}}'

tasks:
    tsc: tsc
    test: vitest 'src/**/*.test.js'

    lint:prettier:
        vars:
            PRETTIER_ARG: '{{if eq .FIX "false"}}--check{{else}}--write{{end}}'
        cmds:
            - prettier {{.PRETTIER_ARG}} {{.FILES | default '.'}}

    eslint: eslint {{if ne .FIX "false"}}--fix{{end}} {{ .ESLINT_TARGET }}

    check:fix:delta:
        vars:
            FILES:
                sh: git diff-ls --diff-filter=d {{ .TARGET_BRANCH | default "main" }}
        cmds:
            - task: 'lint:prettier'
              vars: { FIX: 'true', FILES: '{{.FILES}}' }

    check:
        deps: [prettier, eslint, test]

    'check:lite':
        deps: [tsc, test]

    'check:fix':
        cmds:
            - git status | grep 'nothing to commit, working tree clean'
            - task: prettier
              vars: { FIX: true }
            - cmd: git commit -m prettier .
              ignore_error: true
            - task: eslint
              vars: { FIX: true }
            - cmd: git commit -m eslint .
              ignore_error: true
            - task: check:lite

    integrate:
        deps: [check]
        cmds:
            - git checkout {{.B}}
            - git weld - --no-edit
        preconditions:
            - test -n "{{.B}}"

    changed:
        cmds:
            - echo {{.CHANGED | catLines}}

    'is-clean':
        cmds:
            - git is-clean

    'test:snapshots':
        cmds:
            - jest src -u
