version: 3

vars:
    CHANGED:
        sh: git diff-ls main | grep '\.ts$'

tasks:
    tsc: tsc
    test: jest

    'prettier:fix': prettier --write .
    prettier: prettier --check .

    check:
        deps: [tsc, test, prettier]

    changed:
        cmds:
            - echo {{.CHANGED | catLines}}
    'eslint:incr':
        cmds:
            - eslint {{.CHANGED | catLines}}
    'prettier:incr':
        cmds:
            - prettier -c {{.CHANGED | catLines}}
    'prettier:incr:fix':
        cmds:
            - prettier --write {{.CHANGED | catLines}}
    'is-clean':
        cmds:
            - git is-clean

    'test:snapshots':
        cmds:
            - jest src -u
    integrate:
        deps:
            - is-clean
            - test
            - 'prettier:incr'
            - 'eslint:incr'
        cmds:
            - echo good to go
