version: 3

vars:
    FIX: false
    DIFF: false
    BASE: main
    SNAPSHOT: false
    CHANGED:
        sh: git diff-ls --diff-filter=d {{.BASE | default "main" }}
    PRETTIER_TARGET: '{{if eq .DIFF "false"}}.{{else}}{{.CHANGED | catLines}}{{end}}'
    ESLINT_TARGET: '{{if eq .DIFF "false"}}src{{else}}{{.CHANGED | catLines}}{{end}}'

tasks:
    test: npx vitest run

    prettier:
        vars:
            PRETTIER_ARG: '{{if eq .FIX "false"}}--check{{else}}--write{{end}}'
            FILES: &files '{{ if eq .DELTA "" }}.{{else}}{{.CHANGED}}{{end}}'
        cmds:
            - prettier {{.PRETTIER_ARG}} {{.FILES | catLines}}

    eslint:
        vars:
            FILES: *files
        cmds:
            - npx eslint {{if ne .FIX ""}}--fix{{end}} {{ .FILES | catLines }}

    checks:
        cmds:
            - task: prettier
            - task: eslint
            - task: test

    integrate:
        deps: ['is-clean', checks]
        cmds:
            - git checkout {{.BASE | default "main"}}
            - git weld - --no-edit

    'is-clean':
        cmds:
            - git is-clean

    'test:snapshots':
        cmds:
            - jest src -u
