version: 3

vars:
    CHANGED:
        sh: git diff-ls main | grep '\.ts$'

tasks:
    tsc: tsc
    test: jest

    'prettier:fix': prettier --write .
    prettier: prettier --check .

    eslint: eslint src
    'eslint:fix': eslint --fix src

    check:
        deps: [prettier, eslint, 'check:lite']

    'check:lite':
        deps: [tsc, test]

    'check:fix':
        cmds:
            - git status | grep 'nothing to commit, working tree clean'
            - task: prettier:fix
            - cmd: git commit -m prettier .
              ignore_error: true
            - task: eslint:fix
            - cmd: git commit -m eslint .
              ignore_error: true
            - task: check:lite

    integrate:
        deps: [check:fix]
        cmds:
            - git checkout {{.B}}
            - git weld {{.B}}
        preconditions:
            - test -n "{{.B}}"

    changed:
        cmds:
            - echo {{.CHANGED | catLines}}
    'eslint:incr':
        cmds:
            - eslint {{.CHANGED | catLines}}
    'prettier:incr':
        cmds:
            - prettier -c {{.CHANGED | catLines}}
    'prettier:incr:fix':
        cmds:
            - prettier --write {{.CHANGED | catLines}}
    'is-clean':
        cmds:
            - git is-clean

    'test:snapshots':
        cmds:
            - jest src -u
